version: '3.1'

services:
  web:
    build: .
    ports:
      - "8080:8080"
      - "443:443"
    depends_on:
      - db
    volumes:
      - /your/directory/secretshare:/var/www/html
      - /your/directory/secretshare/certs:/etc/ssl/certs
      - /your/directory/secretshare/default-ssl.conf:/etc/apache2/sites-available/default-ssl.conf
    

  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: 'database name'
      MYSQL_USER: 'DB user'
      MYSQL_PASSWORD: 'DB user password'
      MYSQL_ROOT_PASSWORD: 'DB root password'
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
